version: "3.8"

services:
  client:
    container_name: to-dos-client
    build: 
      context: ./client
      target: production
    ports:
      - 4200:4200

  server:
    container_name: to-dos-server
    build:
      context: ./server
      target: production
    image: to-dos-server
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    links:
      - db
    volumes:
      - './:/src'

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql