name: Google Cloud Run Deployment
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: my-to-dos-378409
  RUN_REGION: australia-southeast1
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY }}
  IMAGE_NAME: my-to-dos
  SERVICE: my-to-dos
jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GCP authentication
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ env.SA_KEY_JSON }}'

      - name: Setup gcloud CLI
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: ">= 363.0.0"
          project_id: ${{ env.PROJECT_ID }}

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:$GITHUB_SHA . 

      # Docker requires privileged access to interact with registries, this is the step to authenticate docker to access GCR
      - name: Authenticate Docker 
        run:  gcloud auth configure-docker --quiet 
        
      - name: Push Docker Image to Google Container Registry 
        run: |-
          docker tag $IMAGE_NAME:$GITHUB_SHA gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA 
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA 

      - name: Deploy
        run: gcloud run deploy $PROJECT_ID --image gcr.io/$PROJECT_ID/$IMAGE_NAME:$GITHUB_SHA --platform managed --region $RUN_REGION